# Generated by Django 3.2.20 on 2023-10-11 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contct',
            new_name='contact',
        ),
    ]
